#!/usr/bin/env bash
# Ommiting superstious numbers in China, Japan and  Italy using while loop
#+ and case statement
i=1;
while (( i<=20 ));
do
	case "$i" in
		4)
	 	echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
		*)
		echo $i
		;;
	esac
	(( i++ ))
done
